name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Clone the SQLite Cloud docs repository
        run: git clone https://github.com/sqlitecloud/docs
        shell: bash
      - uses: ./
        with:
          connection_string: ${{ secrets.CONNECTION_STRING }}
          base_url: https://docs.sqlitecloud.io/docs/
          database: aisearch-action-test.sqlite
          source_files: docs